# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancleHf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CancelId', models.CharField(default='0_0', max_length=128, unique=True, verbose_name='取关编号')),
                ('state', models.IntegerField(default=0, verbose_name='取关状态')),
                ('cancel_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取关时间')),
                ('cancle_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCancel', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserDo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HufenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HufenId', models.CharField(default='0_0', max_length=128, unique=True, verbose_name='互粉编号')),
                ('state', models.IntegerField(default=0, verbose_name='匹配状态')),
                ('errinfo', models.CharField(default='NoError', max_length=256, verbose_name='异常信息')),
                ('hftime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('bguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bguser', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHeadProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('headurl', models.CharField(max_length=256, verbose_name='头像链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserHead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
